# Generated by Django 3.0.4 on 2020-03-26 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0004_movrotativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensalista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('valor_mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamento.Paramentros')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamento.Veiculo')),
            ],
        ),
    ]
